Non-Sequencer gets a new icon! Set icon on main window. Requires libXpm. Also, update config funcs.

diff --git a/scripts/config-funcs b/scripts/config-funcs
--- a/scripts/config-funcs
+++ b/scripts/config-funcs
@@ -127,13 +127,18 @@ ask ()
 
 ok ()
 {
-    echo -e '\r'`tput cuf 30`"$BOLD${GREEN}ok${SGR0} ${*:+${BOLD}${BLACK}($*)${SGR0}}"
+    echo '\r'`tput cuf 30`"$BOLD${GREEN}ok${SGR0} ${*:+${BOLD}${BLACK}($*)${SGR0}}"
 }
 
 failed ()
 {
-    echo "$BOLD${RED}failed!${SGR0}" > /dev/stderr
+    echo '\r'`tput cuf 30`"$BOLD${RED}failed!${SGR0}" > /dev/stderr
     rm -f .config
+}
+
+missing ()
+{
+    echo '\r'`tput cuf 30`"$BOLD${YELLOW}missing!${SGR0}" > /dev/stderr
 }
 
 using ()
@@ -178,6 +183,7 @@ extract_options ()
 begin ()
 {
     echo -n "Checking sanity..."
+    require_command tput tput > /dev/null
     require_command pkg-config pkg-config > /dev/null
     require_command sed sed > /dev/null
     ok
@@ -280,13 +286,48 @@ require_package ()
     return 0
 }
 
+suggest_package ()
+{
+   local name
+
+    echo -n "Checking for $BOLD$1$SGR0..."
+    if ! pkg-config --exists $3
+    then
+    	missing
+	warn "Suggested package $1 doesn't appear to be installed. Some functionality may be missing from your build."
+        warn "Continuing without $1...\n"
+        return 1;
+    elif ! pkg-config --atleast-version $2 $3
+    then
+        missing
+        warn "The installed version of suggested package $1 (`pkg-config --mod-version $3`) is too old."
+        warn "Continuing without $1..."
+        return 1;
+    fi
+
+    name="`upcase \"$1\"`"
+    append "${name}_LIBS=`pkg-config --libs $3 | sed 's/,\\?--as-needed//g'`"
+    append "${name}_CFLAGS=-DHAVE_${1} `pkg-config --cflags $3`"
+
+    ok `pkg-config --modversion "$3"`
+    return 0
+}
+
 _test_version ()
 {
-    [ $1 -gt $4 ] && return 0
-    [ $1 -eq $4 ] && [ $2 -gt $5 ] && return 0
-    [ $1 -eq $4 ] && [ $2 -eq $5 ] && [ $3 -gt $6 ] && return 0
-    [ $1 -eq $4 ] && [ $2 -eq $5 ] && [ $3 -eq $6 ] && return 0
-    return 1
+    if [ $# = 6 ]
+    then
+        [ $1 -gt $4 ] && return 0
+        [ $1 -eq $4 ] && [ $2 -gt $5 ] && return 0
+        [ $1 -eq $4 ] && [ $2 -eq $5 ] && [ $3 -gt $6 ] && return 0
+        [ $1 -eq $4 ] && [ $2 -eq $5 ] && [ $3 -eq $6 ] && return 0
+        return 1
+    elif [ $# = 4 ]
+    then
+        [ $1 -gt $3 ] && return 0
+        [ $1 -eq $3 ] && [ $2 -eq $4 ] && return 0
+        return 1
+    fi
 }
 
 # return true if #1 is greater than or equal to $2
